#!/usr/bin/python

import subprocess
import sys, getopt
import os

def main(argv):
  limit = 5000000
  browser = 0
  precision = 0
  b_found = False
  p_found = False
  tests = 'main'
  output_file = 'tests/e.out'
  try :
    opts, args = getopt.getopt(argv, "hb:p:o:t:")
  except getopt.GetoptError:
    print 'ERROR : run.py -b <browser> -p <precision> <input_filename>'
    sys.exit(2)
  for opt, arg in opts:
    if opt == '-h':
      print 'ERROR : run.py -b <browser> -p <precision> <input_filename>'
      sys.exit()
    elif opt == '-b':
      b_found = True
      if arg == 'chrome':
        browser = 0
      elif arg == 'firefox':
        browser = 1
      else:
        print 'Error in browser argument. Usage : run.py -b <browser> -p <precision> <input_filename>'
        sys.exit()
    elif opt == '-p':
      p_found = True
      if arg == 'single':
        precision = 0
      elif arg == 'double':
        precision = 1
      else:
        print 'Error in precision argument. Usage : run.py -b <browser> -p <precision> <input_filename>'
        sys.exit()
    elif opt == '-o':
      output_file = arg
    elif opt == '-t':
      tests = arg
  if not b_found or not p_found :
    print 'run.py -b <browser> -p <precision> <input_filename>'
    sys.exit()
  arg = args[0] 
  #ls = subprocess.Popen(["wc", "-l", arg], stdout=subprocess.PIPE)
  #size = int(ls.communicate()[0].split()[0])
  basename = os.path.basename(arg)
  #loc = os.path.join(os.getcwd(),basename)
  status = subprocess.call('cp ' + arg + ' ' + basename, shell=True)
  #split = subprocess.Popen(["split", "-l", str(limit), "-d", '--additional-suffix=.mtx', arg, loc], stdout=subprocess.PIPE)
  #split.communicate()
  #if size > limit:
    #num = size/limit
  #else:
    #num = 0
  #if size % limit:
    #num = num + 1;
  #line1 = "var num = " + str(num) 
  #line1 = "var filename = '" + os.path.splitext(basename)[0] + "'"  
  line1 = "var filename = '" + basename + "'"  
  line2 = "var browser = " + str(browser)
  line3 = "var output_file = '" + output_file + "'"
  #line4 = "let TOTAL_MEMORY = 2147418112"
  #if browser == 1:
    #line4 = "let TOTAL_MEMORY = 16777216" 
  with open('input.js', 'w') as g:
    g.write(line1 + '\n' + line2 + '\n' + line3 + '\n')
  httpd = subprocess.Popen(["python", "web.py"], stdout=subprocess.PIPE)
  url = "http://localhost:8080/static/tests/"+tests+"32.html"
  if precision == 1:
    url = "http://localhost:8080/static/tests/"+tests+"64.html"
  #browser_path = r'google-chrome'
  browser_path = r'/mnt/local/HDD_data/cheetah/chrome97/opt/google/chrome/chrome'
  browser_opts = ' '
  browser_opts = ' '.join(["--js-flags=\"--experimental-wasm-simd\"", "--headless --remote-debugging-address=0.0.0.0 --remote-debugging-port=9222 --enable-features=SharedArrayBuffer --enable-logging=stderr --v=1 > log.txt 2>&1"])
  if browser == 1:
    browser_path = r'/mnt/cheetah/firefox68/firefox/firefox'
    browser_opts = '-new-instance'
    #browser_path = r'firefox'
    #browser_path = r'/mnt/local/cheetah/firefox59/firefox'
  #browser_opts = ' '.join(["--no-sandbox", "--incognito", "--js-flags=\"--print-opt-code --print-opt-code-filter=spmv_coo --code-comments\""])
  #browser_opts = ' '.join(["--js-flags=\"--max-new-space-size=8192\""])
  invocation = browser_path + " " + browser_opts + " " + url 
  print invocation
  p = subprocess.Popen(invocation, stdout=subprocess.PIPE, stderr=subprocess.PIPE, shell=True)
  out, err = p.communicate()
  print out
  httpd.terminate()
  status = subprocess.call('rm ' + os.path.splitext(basename)[0] + '.mtx', shell=True)

if __name__ == "__main__":
  main(sys.argv[1:])

